# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import dataclasses
import urllib.request
from typing import Any
from typing import Dict

import h5py
import io
import torch as t

import corenet.file_system as efs
from corenet import cmd_line_flags

tensor_map = {
    "stage1.conv.bias": "conv1/conv1_b:0",
    "stage1.conv.weight": "conv1/conv1_W:0",
    "stage1_part2.bn.bias": "bn_conv1/bn_conv1_beta:0",
    "stage1_part2.bn.running_mean": "bn_conv1/bn_conv1_running_mean:0",
    "stage1_part2.bn.running_var": "bn_conv1/bn_conv1_running_std:0",
    "stage1_part2.bn.weight": "bn_conv1/bn_conv1_gamma:0",
    "stage2.a.op_a.bn.bias": "bn2a_branch2a/bn2a_branch2a_beta:0",
    "stage2.a.op_a.bn.running_mean": "bn2a_branch2a/bn2a_branch2a_running_mean:0",
    "stage2.a.op_a.bn.running_var": "bn2a_branch2a/bn2a_branch2a_running_std:0",
    "stage2.a.op_a.bn.weight": "bn2a_branch2a/bn2a_branch2a_gamma:0",
    "stage2.a.op_a.conv.bias": "res2a_branch2a/res2a_branch2a_b:0",
    "stage2.a.op_a.conv.weight": "res2a_branch2a/res2a_branch2a_W:0",
    "stage2.a.op_b.bn.bias": "bn2a_branch2b/bn2a_branch2b_beta:0",
    "stage2.a.op_b.bn.running_mean": "bn2a_branch2b/bn2a_branch2b_running_mean:0",
    "stage2.a.op_b.bn.running_var": "bn2a_branch2b/bn2a_branch2b_running_std:0",
    "stage2.a.op_b.bn.weight": "bn2a_branch2b/bn2a_branch2b_gamma:0",
    "stage2.a.op_b.conv.bias": "res2a_branch2b/res2a_branch2b_b:0",
    "stage2.a.op_b.conv.weight": "res2a_branch2b/res2a_branch2b_W:0",
    "stage2.a.op_c.bn.bias": "bn2a_branch2c/bn2a_branch2c_beta:0",
    "stage2.a.op_c.bn.running_mean": "bn2a_branch2c/bn2a_branch2c_running_mean:0",
    "stage2.a.op_c.bn.running_var": "bn2a_branch2c/bn2a_branch2c_running_std:0",
    "stage2.a.op_c.bn.weight": "bn2a_branch2c/bn2a_branch2c_gamma:0",
    "stage2.a.op_c.conv.bias": "res2a_branch2c/res2a_branch2c_b:0",
    "stage2.a.op_c.conv.weight": "res2a_branch2c/res2a_branch2c_W:0",
    "stage2.a.shortcut.bn.bias": "bn2a_branch1/bn2a_branch1_beta:0",
    "stage2.a.shortcut.bn.running_mean": "bn2a_branch1/bn2a_branch1_running_mean:0",
    "stage2.a.shortcut.bn.running_var": "bn2a_branch1/bn2a_branch1_running_std:0",
    "stage2.a.shortcut.bn.weight": "bn2a_branch1/bn2a_branch1_gamma:0",
    "stage2.a.shortcut.conv.bias": "res2a_branch1/res2a_branch1_b:0",
    "stage2.a.shortcut.conv.weight": "res2a_branch1/res2a_branch1_W:0",
    "stage2.b.op_a.bn.bias": "bn2b_branch2a/bn2b_branch2a_beta:0",
    "stage2.b.op_a.bn.running_mean": "bn2b_branch2a/bn2b_branch2a_running_mean:0",
    "stage2.b.op_a.bn.running_var": "bn2b_branch2a/bn2b_branch2a_running_std:0",
    "stage2.b.op_a.bn.weight": "bn2b_branch2a/bn2b_branch2a_gamma:0",
    "stage2.b.op_a.conv.bias": "res2b_branch2a/res2b_branch2a_b:0",
    "stage2.b.op_a.conv.weight": "res2b_branch2a/res2b_branch2a_W:0",
    "stage2.b.op_b.bn.bias": "bn2b_branch2b/bn2b_branch2b_beta:0",
    "stage2.b.op_b.bn.running_mean": "bn2b_branch2b/bn2b_branch2b_running_mean:0",
    "stage2.b.op_b.bn.running_var": "bn2b_branch2b/bn2b_branch2b_running_std:0",
    "stage2.b.op_b.bn.weight": "bn2b_branch2b/bn2b_branch2b_gamma:0",
    "stage2.b.op_b.conv.bias": "res2b_branch2b/res2b_branch2b_b:0",
    "stage2.b.op_b.conv.weight": "res2b_branch2b/res2b_branch2b_W:0",
    "stage2.b.op_c.bn.bias": "bn2b_branch2c/bn2b_branch2c_beta:0",
    "stage2.b.op_c.bn.running_mean": "bn2b_branch2c/bn2b_branch2c_running_mean:0",
    "stage2.b.op_c.bn.running_var": "bn2b_branch2c/bn2b_branch2c_running_std:0",
    "stage2.b.op_c.bn.weight": "bn2b_branch2c/bn2b_branch2c_gamma:0",
    "stage2.b.op_c.conv.bias": "res2b_branch2c/res2b_branch2c_b:0",
    "stage2.b.op_c.conv.weight": "res2b_branch2c/res2b_branch2c_W:0",
    "stage2.c.op_a.bn.bias": "bn2c_branch2a/bn2c_branch2a_beta:0",
    "stage2.c.op_a.bn.running_mean": "bn2c_branch2a/bn2c_branch2a_running_mean:0",
    "stage2.c.op_a.bn.running_var": "bn2c_branch2a/bn2c_branch2a_running_std:0",
    "stage2.c.op_a.bn.weight": "bn2c_branch2a/bn2c_branch2a_gamma:0",
    "stage2.c.op_a.conv.bias": "res2c_branch2a/res2c_branch2a_b:0",
    "stage2.c.op_a.conv.weight": "res2c_branch2a/res2c_branch2a_W:0",
    "stage2.c.op_b.bn.bias": "bn2c_branch2b/bn2c_branch2b_beta:0",
    "stage2.c.op_b.bn.running_mean": "bn2c_branch2b/bn2c_branch2b_running_mean:0",
    "stage2.c.op_b.bn.running_var": "bn2c_branch2b/bn2c_branch2b_running_std:0",
    "stage2.c.op_b.bn.weight": "bn2c_branch2b/bn2c_branch2b_gamma:0",
    "stage2.c.op_b.conv.bias": "res2c_branch2b/res2c_branch2b_b:0",
    "stage2.c.op_b.conv.weight": "res2c_branch2b/res2c_branch2b_W:0",
    "stage2.c.op_c.bn.bias": "bn2c_branch2c/bn2c_branch2c_beta:0",
    "stage2.c.op_c.bn.running_mean": "bn2c_branch2c/bn2c_branch2c_running_mean:0",
    "stage2.c.op_c.bn.running_var": "bn2c_branch2c/bn2c_branch2c_running_std:0",
    "stage2.c.op_c.bn.weight": "bn2c_branch2c/bn2c_branch2c_gamma:0",
    "stage2.c.op_c.conv.bias": "res2c_branch2c/res2c_branch2c_b:0",
    "stage2.c.op_c.conv.weight": "res2c_branch2c/res2c_branch2c_W:0",
    "stage3.a.op_a.bn.bias": "bn3a_branch2a/bn3a_branch2a_beta:0",
    "stage3.a.op_a.bn.running_mean": "bn3a_branch2a/bn3a_branch2a_running_mean:0",
    "stage3.a.op_a.bn.running_var": "bn3a_branch2a/bn3a_branch2a_running_std:0",
    "stage3.a.op_a.bn.weight": "bn3a_branch2a/bn3a_branch2a_gamma:0",
    "stage3.a.op_a.conv.bias": "res3a_branch2a/res3a_branch2a_b:0",
    "stage3.a.op_a.conv.weight": "res3a_branch2a/res3a_branch2a_W:0",
    "stage3.a.op_b.bn.bias": "bn3a_branch2b/bn3a_branch2b_beta:0",
    "stage3.a.op_b.bn.running_mean": "bn3a_branch2b/bn3a_branch2b_running_mean:0",
    "stage3.a.op_b.bn.running_var": "bn3a_branch2b/bn3a_branch2b_running_std:0",
    "stage3.a.op_b.bn.weight": "bn3a_branch2b/bn3a_branch2b_gamma:0",
    "stage3.a.op_b.conv.bias": "res3a_branch2b/res3a_branch2b_b:0",
    "stage3.a.op_b.conv.weight": "res3a_branch2b/res3a_branch2b_W:0",
    "stage3.a.op_c.bn.bias": "bn3a_branch2c/bn3a_branch2c_beta:0",
    "stage3.a.op_c.bn.running_mean": "bn3a_branch2c/bn3a_branch2c_running_mean:0",
    "stage3.a.op_c.bn.running_var": "bn3a_branch2c/bn3a_branch2c_running_std:0",
    "stage3.a.op_c.bn.weight": "bn3a_branch2c/bn3a_branch2c_gamma:0",
    "stage3.a.op_c.conv.bias": "res3a_branch2c/res3a_branch2c_b:0",
    "stage3.a.op_c.conv.weight": "res3a_branch2c/res3a_branch2c_W:0",
    "stage3.a.shortcut.bn.bias": "bn3a_branch1/bn3a_branch1_beta:0",
    "stage3.a.shortcut.bn.running_mean": "bn3a_branch1/bn3a_branch1_running_mean:0",
    "stage3.a.shortcut.bn.running_var": "bn3a_branch1/bn3a_branch1_running_std:0",
    "stage3.a.shortcut.bn.weight": "bn3a_branch1/bn3a_branch1_gamma:0",
    "stage3.a.shortcut.conv.bias": "res3a_branch1/res3a_branch1_b:0",
    "stage3.a.shortcut.conv.weight": "res3a_branch1/res3a_branch1_W:0",
    "stage3.b.op_a.bn.bias": "bn3b_branch2a/bn3b_branch2a_beta:0",
    "stage3.b.op_a.bn.running_mean": "bn3b_branch2a/bn3b_branch2a_running_mean:0",
    "stage3.b.op_a.bn.running_var": "bn3b_branch2a/bn3b_branch2a_running_std:0",
    "stage3.b.op_a.bn.weight": "bn3b_branch2a/bn3b_branch2a_gamma:0",
    "stage3.b.op_a.conv.bias": "res3b_branch2a/res3b_branch2a_b:0",
    "stage3.b.op_a.conv.weight": "res3b_branch2a/res3b_branch2a_W:0",
    "stage3.b.op_b.bn.bias": "bn3b_branch2b/bn3b_branch2b_beta:0",
    "stage3.b.op_b.bn.running_mean": "bn3b_branch2b/bn3b_branch2b_running_mean:0",
    "stage3.b.op_b.bn.running_var": "bn3b_branch2b/bn3b_branch2b_running_std:0",
    "stage3.b.op_b.bn.weight": "bn3b_branch2b/bn3b_branch2b_gamma:0",
    "stage3.b.op_b.conv.bias": "res3b_branch2b/res3b_branch2b_b:0",
    "stage3.b.op_b.conv.weight": "res3b_branch2b/res3b_branch2b_W:0",
    "stage3.b.op_c.bn.bias": "bn3b_branch2c/bn3b_branch2c_beta:0",
    "stage3.b.op_c.bn.running_mean": "bn3b_branch2c/bn3b_branch2c_running_mean:0",
    "stage3.b.op_c.bn.running_var": "bn3b_branch2c/bn3b_branch2c_running_std:0",
    "stage3.b.op_c.bn.weight": "bn3b_branch2c/bn3b_branch2c_gamma:0",
    "stage3.b.op_c.conv.bias": "res3b_branch2c/res3b_branch2c_b:0",
    "stage3.b.op_c.conv.weight": "res3b_branch2c/res3b_branch2c_W:0",
    "stage3.c.op_a.bn.bias": "bn3c_branch2a/bn3c_branch2a_beta:0",
    "stage3.c.op_a.bn.running_mean": "bn3c_branch2a/bn3c_branch2a_running_mean:0",
    "stage3.c.op_a.bn.running_var": "bn3c_branch2a/bn3c_branch2a_running_std:0",
    "stage3.c.op_a.bn.weight": "bn3c_branch2a/bn3c_branch2a_gamma:0",
    "stage3.c.op_a.conv.bias": "res3c_branch2a/res3c_branch2a_b:0",
    "stage3.c.op_a.conv.weight": "res3c_branch2a/res3c_branch2a_W:0",
    "stage3.c.op_b.bn.bias": "bn3c_branch2b/bn3c_branch2b_beta:0",
    "stage3.c.op_b.bn.running_mean": "bn3c_branch2b/bn3c_branch2b_running_mean:0",
    "stage3.c.op_b.bn.running_var": "bn3c_branch2b/bn3c_branch2b_running_std:0",
    "stage3.c.op_b.bn.weight": "bn3c_branch2b/bn3c_branch2b_gamma:0",
    "stage3.c.op_b.conv.bias": "res3c_branch2b/res3c_branch2b_b:0",
    "stage3.c.op_b.conv.weight": "res3c_branch2b/res3c_branch2b_W:0",
    "stage3.c.op_c.bn.bias": "bn3c_branch2c/bn3c_branch2c_beta:0",
    "stage3.c.op_c.bn.running_mean": "bn3c_branch2c/bn3c_branch2c_running_mean:0",
    "stage3.c.op_c.bn.running_var": "bn3c_branch2c/bn3c_branch2c_running_std:0",
    "stage3.c.op_c.bn.weight": "bn3c_branch2c/bn3c_branch2c_gamma:0",
    "stage3.c.op_c.conv.bias": "res3c_branch2c/res3c_branch2c_b:0",
    "stage3.c.op_c.conv.weight": "res3c_branch2c/res3c_branch2c_W:0",
    "stage3.d.op_a.bn.bias": "bn3d_branch2a/bn3d_branch2a_beta:0",
    "stage3.d.op_a.bn.running_mean": "bn3d_branch2a/bn3d_branch2a_running_mean:0",
    "stage3.d.op_a.bn.running_var": "bn3d_branch2a/bn3d_branch2a_running_std:0",
    "stage3.d.op_a.bn.weight": "bn3d_branch2a/bn3d_branch2a_gamma:0",
    "stage3.d.op_a.conv.bias": "res3d_branch2a/res3d_branch2a_b:0",
    "stage3.d.op_a.conv.weight": "res3d_branch2a/res3d_branch2a_W:0",
    "stage3.d.op_b.bn.bias": "bn3d_branch2b/bn3d_branch2b_beta:0",
    "stage3.d.op_b.bn.running_mean": "bn3d_branch2b/bn3d_branch2b_running_mean:0",
    "stage3.d.op_b.bn.running_var": "bn3d_branch2b/bn3d_branch2b_running_std:0",
    "stage3.d.op_b.bn.weight": "bn3d_branch2b/bn3d_branch2b_gamma:0",
    "stage3.d.op_b.conv.bias": "res3d_branch2b/res3d_branch2b_b:0",
    "stage3.d.op_b.conv.weight": "res3d_branch2b/res3d_branch2b_W:0",
    "stage3.d.op_c.bn.bias": "bn3d_branch2c/bn3d_branch2c_beta:0",
    "stage3.d.op_c.bn.running_mean": "bn3d_branch2c/bn3d_branch2c_running_mean:0",
    "stage3.d.op_c.bn.running_var": "bn3d_branch2c/bn3d_branch2c_running_std:0",
    "stage3.d.op_c.bn.weight": "bn3d_branch2c/bn3d_branch2c_gamma:0",
    "stage3.d.op_c.conv.bias": "res3d_branch2c/res3d_branch2c_b:0",
    "stage3.d.op_c.conv.weight": "res3d_branch2c/res3d_branch2c_W:0",
    "stage4.a.op_a.bn.bias": "bn4a_branch2a/bn4a_branch2a_beta:0",
    "stage4.a.op_a.bn.running_mean": "bn4a_branch2a/bn4a_branch2a_running_mean:0",
    "stage4.a.op_a.bn.running_var": "bn4a_branch2a/bn4a_branch2a_running_std:0",
    "stage4.a.op_a.bn.weight": "bn4a_branch2a/bn4a_branch2a_gamma:0",
    "stage4.a.op_a.conv.bias": "res4a_branch2a/res4a_branch2a_b:0",
    "stage4.a.op_a.conv.weight": "res4a_branch2a/res4a_branch2a_W:0",
    "stage4.a.op_b.bn.bias": "bn4a_branch2b/bn4a_branch2b_beta:0",
    "stage4.a.op_b.bn.running_mean": "bn4a_branch2b/bn4a_branch2b_running_mean:0",
    "stage4.a.op_b.bn.running_var": "bn4a_branch2b/bn4a_branch2b_running_std:0",
    "stage4.a.op_b.bn.weight": "bn4a_branch2b/bn4a_branch2b_gamma:0",
    "stage4.a.op_b.conv.bias": "res4a_branch2b/res4a_branch2b_b:0",
    "stage4.a.op_b.conv.weight": "res4a_branch2b/res4a_branch2b_W:0",
    "stage4.a.op_c.bn.bias": "bn4a_branch2c/bn4a_branch2c_beta:0",
    "stage4.a.op_c.bn.running_mean": "bn4a_branch2c/bn4a_branch2c_running_mean:0",
    "stage4.a.op_c.bn.running_var": "bn4a_branch2c/bn4a_branch2c_running_std:0",
    "stage4.a.op_c.bn.weight": "bn4a_branch2c/bn4a_branch2c_gamma:0",
    "stage4.a.op_c.conv.bias": "res4a_branch2c/res4a_branch2c_b:0",
    "stage4.a.op_c.conv.weight": "res4a_branch2c/res4a_branch2c_W:0",
    "stage4.a.shortcut.bn.bias": "bn4a_branch1/bn4a_branch1_beta:0",
    "stage4.a.shortcut.bn.running_mean": "bn4a_branch1/bn4a_branch1_running_mean:0",
    "stage4.a.shortcut.bn.running_var": "bn4a_branch1/bn4a_branch1_running_std:0",
    "stage4.a.shortcut.bn.weight": "bn4a_branch1/bn4a_branch1_gamma:0",
    "stage4.a.shortcut.conv.bias": "res4a_branch1/res4a_branch1_b:0",
    "stage4.a.shortcut.conv.weight": "res4a_branch1/res4a_branch1_W:0",
    "stage4.b.op_a.bn.bias": "bn4b_branch2a/bn4b_branch2a_beta:0",
    "stage4.b.op_a.bn.running_mean": "bn4b_branch2a/bn4b_branch2a_running_mean:0",
    "stage4.b.op_a.bn.running_var": "bn4b_branch2a/bn4b_branch2a_running_std:0",
    "stage4.b.op_a.bn.weight": "bn4b_branch2a/bn4b_branch2a_gamma:0",
    "stage4.b.op_a.conv.bias": "res4b_branch2a/res4b_branch2a_b:0",
    "stage4.b.op_a.conv.weight": "res4b_branch2a/res4b_branch2a_W:0",
    "stage4.b.op_b.bn.bias": "bn4b_branch2b/bn4b_branch2b_beta:0",
    "stage4.b.op_b.bn.running_mean": "bn4b_branch2b/bn4b_branch2b_running_mean:0",
    "stage4.b.op_b.bn.running_var": "bn4b_branch2b/bn4b_branch2b_running_std:0",
    "stage4.b.op_b.bn.weight": "bn4b_branch2b/bn4b_branch2b_gamma:0",
    "stage4.b.op_b.conv.bias": "res4b_branch2b/res4b_branch2b_b:0",
    "stage4.b.op_b.conv.weight": "res4b_branch2b/res4b_branch2b_W:0",
    "stage4.b.op_c.bn.bias": "bn4b_branch2c/bn4b_branch2c_beta:0",
    "stage4.b.op_c.bn.running_mean": "bn4b_branch2c/bn4b_branch2c_running_mean:0",
    "stage4.b.op_c.bn.running_var": "bn4b_branch2c/bn4b_branch2c_running_std:0",
    "stage4.b.op_c.bn.weight": "bn4b_branch2c/bn4b_branch2c_gamma:0",
    "stage4.b.op_c.conv.bias": "res4b_branch2c/res4b_branch2c_b:0",
    "stage4.b.op_c.conv.weight": "res4b_branch2c/res4b_branch2c_W:0",
    "stage4.c.op_a.bn.bias": "bn4c_branch2a/bn4c_branch2a_beta:0",
    "stage4.c.op_a.bn.running_mean": "bn4c_branch2a/bn4c_branch2a_running_mean:0",
    "stage4.c.op_a.bn.running_var": "bn4c_branch2a/bn4c_branch2a_running_std:0",
    "stage4.c.op_a.bn.weight": "bn4c_branch2a/bn4c_branch2a_gamma:0",
    "stage4.c.op_a.conv.bias": "res4c_branch2a/res4c_branch2a_b:0",
    "stage4.c.op_a.conv.weight": "res4c_branch2a/res4c_branch2a_W:0",
    "stage4.c.op_b.bn.bias": "bn4c_branch2b/bn4c_branch2b_beta:0",
    "stage4.c.op_b.bn.running_mean": "bn4c_branch2b/bn4c_branch2b_running_mean:0",
    "stage4.c.op_b.bn.running_var": "bn4c_branch2b/bn4c_branch2b_running_std:0",
    "stage4.c.op_b.bn.weight": "bn4c_branch2b/bn4c_branch2b_gamma:0",
    "stage4.c.op_b.conv.bias": "res4c_branch2b/res4c_branch2b_b:0",
    "stage4.c.op_b.conv.weight": "res4c_branch2b/res4c_branch2b_W:0",
    "stage4.c.op_c.bn.bias": "bn4c_branch2c/bn4c_branch2c_beta:0",
    "stage4.c.op_c.bn.running_mean": "bn4c_branch2c/bn4c_branch2c_running_mean:0",
    "stage4.c.op_c.bn.running_var": "bn4c_branch2c/bn4c_branch2c_running_std:0",
    "stage4.c.op_c.bn.weight": "bn4c_branch2c/bn4c_branch2c_gamma:0",
    "stage4.c.op_c.conv.bias": "res4c_branch2c/res4c_branch2c_b:0",
    "stage4.c.op_c.conv.weight": "res4c_branch2c/res4c_branch2c_W:0",
    "stage4.d.op_a.bn.bias": "bn4d_branch2a/bn4d_branch2a_beta:0",
    "stage4.d.op_a.bn.running_mean": "bn4d_branch2a/bn4d_branch2a_running_mean:0",
    "stage4.d.op_a.bn.running_var": "bn4d_branch2a/bn4d_branch2a_running_std:0",
    "stage4.d.op_a.bn.weight": "bn4d_branch2a/bn4d_branch2a_gamma:0",
    "stage4.d.op_a.conv.bias": "res4d_branch2a/res4d_branch2a_b:0",
    "stage4.d.op_a.conv.weight": "res4d_branch2a/res4d_branch2a_W:0",
    "stage4.d.op_b.bn.bias": "bn4d_branch2b/bn4d_branch2b_beta:0",
    "stage4.d.op_b.bn.running_mean": "bn4d_branch2b/bn4d_branch2b_running_mean:0",
    "stage4.d.op_b.bn.running_var": "bn4d_branch2b/bn4d_branch2b_running_std:0",
    "stage4.d.op_b.bn.weight": "bn4d_branch2b/bn4d_branch2b_gamma:0",
    "stage4.d.op_b.conv.bias": "res4d_branch2b/res4d_branch2b_b:0",
    "stage4.d.op_b.conv.weight": "res4d_branch2b/res4d_branch2b_W:0",
    "stage4.d.op_c.bn.bias": "bn4d_branch2c/bn4d_branch2c_beta:0",
    "stage4.d.op_c.bn.running_mean": "bn4d_branch2c/bn4d_branch2c_running_mean:0",
    "stage4.d.op_c.bn.running_var": "bn4d_branch2c/bn4d_branch2c_running_std:0",
    "stage4.d.op_c.bn.weight": "bn4d_branch2c/bn4d_branch2c_gamma:0",
    "stage4.d.op_c.conv.bias": "res4d_branch2c/res4d_branch2c_b:0",
    "stage4.d.op_c.conv.weight": "res4d_branch2c/res4d_branch2c_W:0",
    "stage4.e.op_a.bn.bias": "bn4e_branch2a/bn4e_branch2a_beta:0",
    "stage4.e.op_a.bn.running_mean": "bn4e_branch2a/bn4e_branch2a_running_mean:0",
    "stage4.e.op_a.bn.running_var": "bn4e_branch2a/bn4e_branch2a_running_std:0",
    "stage4.e.op_a.bn.weight": "bn4e_branch2a/bn4e_branch2a_gamma:0",
    "stage4.e.op_a.conv.bias": "res4e_branch2a/res4e_branch2a_b:0",
    "stage4.e.op_a.conv.weight": "res4e_branch2a/res4e_branch2a_W:0",
    "stage4.e.op_b.bn.bias": "bn4e_branch2b/bn4e_branch2b_beta:0",
    "stage4.e.op_b.bn.running_mean": "bn4e_branch2b/bn4e_branch2b_running_mean:0",
    "stage4.e.op_b.bn.running_var": "bn4e_branch2b/bn4e_branch2b_running_std:0",
    "stage4.e.op_b.bn.weight": "bn4e_branch2b/bn4e_branch2b_gamma:0",
    "stage4.e.op_b.conv.bias": "res4e_branch2b/res4e_branch2b_b:0",
    "stage4.e.op_b.conv.weight": "res4e_branch2b/res4e_branch2b_W:0",
    "stage4.e.op_c.bn.bias": "bn4e_branch2c/bn4e_branch2c_beta:0",
    "stage4.e.op_c.bn.running_mean": "bn4e_branch2c/bn4e_branch2c_running_mean:0",
    "stage4.e.op_c.bn.running_var": "bn4e_branch2c/bn4e_branch2c_running_std:0",
    "stage4.e.op_c.bn.weight": "bn4e_branch2c/bn4e_branch2c_gamma:0",
    "stage4.e.op_c.conv.bias": "res4e_branch2c/res4e_branch2c_b:0",
    "stage4.e.op_c.conv.weight": "res4e_branch2c/res4e_branch2c_W:0",
    "stage4.f.op_a.bn.bias": "bn4f_branch2a/bn4f_branch2a_beta:0",
    "stage4.f.op_a.bn.running_mean": "bn4f_branch2a/bn4f_branch2a_running_mean:0",
    "stage4.f.op_a.bn.running_var": "bn4f_branch2a/bn4f_branch2a_running_std:0",
    "stage4.f.op_a.bn.weight": "bn4f_branch2a/bn4f_branch2a_gamma:0",
    "stage4.f.op_a.conv.bias": "res4f_branch2a/res4f_branch2a_b:0",
    "stage4.f.op_a.conv.weight": "res4f_branch2a/res4f_branch2a_W:0",
    "stage4.f.op_b.bn.bias": "bn4f_branch2b/bn4f_branch2b_beta:0",
    "stage4.f.op_b.bn.running_mean": "bn4f_branch2b/bn4f_branch2b_running_mean:0",
    "stage4.f.op_b.bn.running_var": "bn4f_branch2b/bn4f_branch2b_running_std:0",
    "stage4.f.op_b.bn.weight": "bn4f_branch2b/bn4f_branch2b_gamma:0",
    "stage4.f.op_b.conv.bias": "res4f_branch2b/res4f_branch2b_b:0",
    "stage4.f.op_b.conv.weight": "res4f_branch2b/res4f_branch2b_W:0",
    "stage4.f.op_c.bn.bias": "bn4f_branch2c/bn4f_branch2c_beta:0",
    "stage4.f.op_c.bn.running_mean": "bn4f_branch2c/bn4f_branch2c_running_mean:0",
    "stage4.f.op_c.bn.running_var": "bn4f_branch2c/bn4f_branch2c_running_std:0",
    "stage4.f.op_c.bn.weight": "bn4f_branch2c/bn4f_branch2c_gamma:0",
    "stage4.f.op_c.conv.bias": "res4f_branch2c/res4f_branch2c_b:0",
    "stage4.f.op_c.conv.weight": "res4f_branch2c/res4f_branch2c_W:0",
    "stage5.a.op_a.bn.bias": "bn5a_branch2a/bn5a_branch2a_beta:0",
    "stage5.a.op_a.bn.running_mean": "bn5a_branch2a/bn5a_branch2a_running_mean:0",
    "stage5.a.op_a.bn.running_var": "bn5a_branch2a/bn5a_branch2a_running_std:0",
    "stage5.a.op_a.bn.weight": "bn5a_branch2a/bn5a_branch2a_gamma:0",
    "stage5.a.op_a.conv.bias": "res5a_branch2a/res5a_branch2a_b:0",
    "stage5.a.op_a.conv.weight": "res5a_branch2a/res5a_branch2a_W:0",
    "stage5.a.op_b.bn.bias": "bn5a_branch2b/bn5a_branch2b_beta:0",
    "stage5.a.op_b.bn.running_mean": "bn5a_branch2b/bn5a_branch2b_running_mean:0",
    "stage5.a.op_b.bn.running_var": "bn5a_branch2b/bn5a_branch2b_running_std:0",
    "stage5.a.op_b.bn.weight": "bn5a_branch2b/bn5a_branch2b_gamma:0",
    "stage5.a.op_b.conv.bias": "res5a_branch2b/res5a_branch2b_b:0",
    "stage5.a.op_b.conv.weight": "res5a_branch2b/res5a_branch2b_W:0",
    "stage5.a.op_c.bn.bias": "bn5a_branch2c/bn5a_branch2c_beta:0",
    "stage5.a.op_c.bn.running_mean": "bn5a_branch2c/bn5a_branch2c_running_mean:0",
    "stage5.a.op_c.bn.running_var": "bn5a_branch2c/bn5a_branch2c_running_std:0",
    "stage5.a.op_c.bn.weight": "bn5a_branch2c/bn5a_branch2c_gamma:0",
    "stage5.a.op_c.conv.bias": "res5a_branch2c/res5a_branch2c_b:0",
    "stage5.a.op_c.conv.weight": "res5a_branch2c/res5a_branch2c_W:0",
    "stage5.a.shortcut.bn.bias": "bn5a_branch1/bn5a_branch1_beta:0",
    "stage5.a.shortcut.bn.running_mean": "bn5a_branch1/bn5a_branch1_running_mean:0",
    "stage5.a.shortcut.bn.running_var": "bn5a_branch1/bn5a_branch1_running_std:0",
    "stage5.a.shortcut.bn.weight": "bn5a_branch1/bn5a_branch1_gamma:0",
    "stage5.a.shortcut.conv.bias": "res5a_branch1/res5a_branch1_b:0",
    "stage5.a.shortcut.conv.weight": "res5a_branch1/res5a_branch1_W:0",
    "stage5.b.op_a.bn.bias": "bn5b_branch2a/bn5b_branch2a_beta:0",
    "stage5.b.op_a.bn.running_mean": "bn5b_branch2a/bn5b_branch2a_running_mean:0",
    "stage5.b.op_a.bn.running_var": "bn5b_branch2a/bn5b_branch2a_running_std:0",
    "stage5.b.op_a.bn.weight": "bn5b_branch2a/bn5b_branch2a_gamma:0",
    "stage5.b.op_a.conv.bias": "res5b_branch2a/res5b_branch2a_b:0",
    "stage5.b.op_a.conv.weight": "res5b_branch2a/res5b_branch2a_W:0",
    "stage5.b.op_b.bn.bias": "bn5b_branch2b/bn5b_branch2b_beta:0",
    "stage5.b.op_b.bn.running_mean": "bn5b_branch2b/bn5b_branch2b_running_mean:0",
    "stage5.b.op_b.bn.running_var": "bn5b_branch2b/bn5b_branch2b_running_std:0",
    "stage5.b.op_b.bn.weight": "bn5b_branch2b/bn5b_branch2b_gamma:0",
    "stage5.b.op_b.conv.bias": "res5b_branch2b/res5b_branch2b_b:0",
    "stage5.b.op_b.conv.weight": "res5b_branch2b/res5b_branch2b_W:0",
    "stage5.b.op_c.bn.bias": "bn5b_branch2c/bn5b_branch2c_beta:0",
    "stage5.b.op_c.bn.running_mean": "bn5b_branch2c/bn5b_branch2c_running_mean:0",
    "stage5.b.op_c.bn.running_var": "bn5b_branch2c/bn5b_branch2c_running_std:0",
    "stage5.b.op_c.bn.weight": "bn5b_branch2c/bn5b_branch2c_gamma:0",
    "stage5.b.op_c.conv.bias": "res5b_branch2c/res5b_branch2c_b:0",
    "stage5.b.op_c.conv.weight": "res5b_branch2c/res5b_branch2c_W:0",
    "stage5.c.op_a.bn.bias": "bn5c_branch2a/bn5c_branch2a_beta:0",
    "stage5.c.op_a.bn.running_mean": "bn5c_branch2a/bn5c_branch2a_running_mean:0",
    "stage5.c.op_a.bn.running_var": "bn5c_branch2a/bn5c_branch2a_running_std:0",
    "stage5.c.op_a.bn.weight": "bn5c_branch2a/bn5c_branch2a_gamma:0",
    "stage5.c.op_a.conv.bias": "res5c_branch2a/res5c_branch2a_b:0",
    "stage5.c.op_a.conv.weight": "res5c_branch2a/res5c_branch2a_W:0",
    "stage5.c.op_b.bn.bias": "bn5c_branch2b/bn5c_branch2b_beta:0",
    "stage5.c.op_b.bn.running_mean": "bn5c_branch2b/bn5c_branch2b_running_mean:0",
    "stage5.c.op_b.bn.running_var": "bn5c_branch2b/bn5c_branch2b_running_std:0",
    "stage5.c.op_b.bn.weight": "bn5c_branch2b/bn5c_branch2b_gamma:0",
    "stage5.c.op_b.conv.bias": "res5c_branch2b/res5c_branch2b_b:0",
    "stage5.c.op_b.conv.weight": "res5c_branch2b/res5c_branch2b_W:0",
    "stage5.c.op_c.bn.bias": "bn5c_branch2c/bn5c_branch2c_beta:0",
    "stage5.c.op_c.bn.running_mean": "bn5c_branch2c/bn5c_branch2c_running_mean:0",
    "stage5.c.op_c.bn.running_var": "bn5c_branch2c/bn5c_branch2c_running_std:0",
    "stage5.c.op_c.bn.weight": "bn5c_branch2c/bn5c_branch2c_gamma:0",
    "stage5.c.op_c.conv.bias": "res5c_branch2c/res5c_branch2c_b:0",
    "stage5.c.op_c.conv.weight": "res5c_branch2c/res5c_branch2c_W:0",

    "stage1_part2.bn.num_batches_tracked": 0,
    "stage2.a.op_a.bn.num_batches_tracked": 0,
    "stage2.a.op_b.bn.num_batches_tracked": 0,
    "stage2.a.op_c.bn.num_batches_tracked": 0,
    "stage2.a.shortcut.bn.num_batches_tracked": 0,
    "stage2.b.op_a.bn.num_batches_tracked": 0,
    "stage2.b.op_b.bn.num_batches_tracked": 0,
    "stage2.b.op_c.bn.num_batches_tracked": 0,
    "stage2.c.op_a.bn.num_batches_tracked": 0,
    "stage2.c.op_b.bn.num_batches_tracked": 0,
    "stage2.c.op_c.bn.num_batches_tracked": 0,
    "stage3.a.op_a.bn.num_batches_tracked": 0,
    "stage3.a.op_b.bn.num_batches_tracked": 0,
    "stage3.a.op_c.bn.num_batches_tracked": 0,
    "stage3.a.shortcut.bn.num_batches_tracked": 0,
    "stage3.b.op_a.bn.num_batches_tracked": 0,
    "stage3.b.op_b.bn.num_batches_tracked": 0,
    "stage3.b.op_c.bn.num_batches_tracked": 0,
    "stage3.c.op_a.bn.num_batches_tracked": 0,
    "stage3.c.op_b.bn.num_batches_tracked": 0,
    "stage3.c.op_c.bn.num_batches_tracked": 0,
    "stage3.d.op_a.bn.num_batches_tracked": 0,
    "stage3.d.op_b.bn.num_batches_tracked": 0,
    "stage3.d.op_c.bn.num_batches_tracked": 0,
    "stage4.a.op_a.bn.num_batches_tracked": 0,
    "stage4.a.op_b.bn.num_batches_tracked": 0,
    "stage4.a.op_c.bn.num_batches_tracked": 0,
    "stage4.a.shortcut.bn.num_batches_tracked": 0,
    "stage4.b.op_a.bn.num_batches_tracked": 0,
    "stage4.b.op_b.bn.num_batches_tracked": 0,
    "stage4.b.op_c.bn.num_batches_tracked": 0,
    "stage4.c.op_a.bn.num_batches_tracked": 0,
    "stage4.c.op_b.bn.num_batches_tracked": 0,
    "stage4.c.op_c.bn.num_batches_tracked": 0,
    "stage4.d.op_a.bn.num_batches_tracked": 0,
    "stage4.d.op_b.bn.num_batches_tracked": 0,
    "stage4.d.op_c.bn.num_batches_tracked": 0,
    "stage4.e.op_a.bn.num_batches_tracked": 0,
    "stage4.e.op_b.bn.num_batches_tracked": 0,
    "stage4.e.op_c.bn.num_batches_tracked": 0,
    "stage4.f.op_a.bn.num_batches_tracked": 0,
    "stage4.f.op_b.bn.num_batches_tracked": 0,
    "stage4.f.op_c.bn.num_batches_tracked": 0,
    "stage5.a.op_a.bn.num_batches_tracked": 0,
    "stage5.a.op_b.bn.num_batches_tracked": 0,
    "stage5.a.op_c.bn.num_batches_tracked": 0,
    "stage5.a.shortcut.bn.num_batches_tracked": 0,
    "stage5.b.op_a.bn.num_batches_tracked": 0,
    "stage5.b.op_b.bn.num_batches_tracked": 0,
    "stage5.b.op_c.bn.num_batches_tracked": 0,
    "stage5.c.op_a.bn.num_batches_tracked": 0,
    "stage5.c.op_b.bn.num_batches_tracked": 0,
    "stage5.c.op_c.bn.num_batches_tracked": 0,
}


def download_check_point():
  url = ("https://github.com/fchollet/deep-learning-models/releases/"
         "download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels.h5")
  print("Downloading ResNet50 checkpoint...")
  content = urllib.request.urlopen(url).read()
  print("Done")
  return content


def convert_tensors(raw_cpt: bytes):
  h5_file = h5py.File(io.BytesIO(raw_cpt), 'r')
  src_tensors = {}  # type: Dict[str, t.Tensor]

  def extract_tensor(name: str, value: Any):
    if isinstance(value, h5py.Dataset):
      src_tensors[name] = t.as_tensor(value)

  h5_file.visititems(extract_tensor)

  output_state_dict = {}
  for k1, k2 in tensor_map.items():
    if k2 == 0:
      output_state_dict[k1] = t.zeros((), dtype=t.int64, device="cpu")
    else:
      v = src_tensors[k2]
      if k2.endswith("_W:0"):
        v = v.permute([3, 2, 0, 1])
      output_state_dict[k1] = v

  return output_state_dict


@dataclasses.dataclass
class Flags:
  raw_output_path: str = cmd_line_flags.flag(
      "Output checkpoint path",
      default="data/raw/resnet50_weights_tf_dim_ordering_tf_kernels.h5")
  output_path: str = cmd_line_flags.flag(
      "Output checkpoint path", default="data/keras_resnet50_imagenet.cpt")


def main():
  flags = cmd_line_flags.parse_flags(Flags)
  raw_cpt = download_check_point()
  efs.write_bytes(flags.raw_output_path, raw_cpt)
  state_dict = convert_tensors(raw_cpt)
  t.save(state_dict, buf := io.BytesIO())
  efs.write_bytes(flags.output_path, buf.getvalue())


if __name__ == '__main__':
  main()
